//  Organization, Side, Specialities, Speed, Difficulty, Year, Squad, Height, Weight, Age, Birth Place
export const Sledge = [         "Sledge",   	"Attacker",     "Breacher, Anti-Gadget",            1, 1,   0,                  "SAS",                      "Redhammer",       	1.92,	95,	    35,	    "Scotland"]
export const Thatcher = [       "Thatcher", 	"Attacker",     "Anti-Gadget, Support",             1, 1,   0,                  "SAS",                      "Viperstrike",     	1.80,	72,	    56,	    "England"]    
export const Ash = [            "Ash",      	"Attacker",     "Breacher, Front-Line",             3, 2,   0,                  "FBI SWAT",                 "Redhammer",       	1.70,	63,	    33,	    "Israel"]
export const Thermite = [       "Thermite", 	"Attacker",     "Breacher, Support",                2, 1,   0,                  "FBI SWAT",                 "Redhammer",       	1.78,	80,	    35,	    "USA"]    
export const Twitch = [         "Twitch",   	"Attacker",     "Intel, Anti-Gadget",               2, 2,   0,                  "GIGN",                     "Wolfguard",       	1.68,	58,	    28,	    "France"]
export const Montagne = [       "Montagne", 	"Attacker",     "Intel, Support",                   1, 3,   0,                  "GIGN",                     "Wolfguard",       	1.90,	90,	    48,	    "France"]    
export const Glaz = [           "Glaz",     	"Attacker",     "Intel, Support",                   3, 2,   0,                  "Spetsnaz",                 "Ghosteyes",       	1.78,	79,	    30,	    "Russia"]
export const Fuze = [           "Fuze",     	"Attacker",     "Anti-Gadget",                      1, 1,   0,                  "Spetsnaz",                 "Redhammer",       	1.80,	80,	    34,	    "Uzbekistan"]
export const Blitz = [          "Blitz",    	"Attacker",     "Front-Line, Map-Control",          2, 3,   0,                  "GSG 9",                    "Viperstrike",     	1.75,	75,	    37,	    "Germany"]
export const Iq = [             "Iq",       	"Attacker",     "Intel, Support",                   3, 3,   0,                  "GSG 9",                    "Nighthaven",      	1.75,	70,	    38,	    "Germany"]
export const Buck = [           "Buck",     	"Attacker",     "Breacher, Support",                2, 1,   1,                  "JTF2",                     "Redhammer",       	1.78,	78,	    36,	    "Canada"]
export const Blackbeard = [     "Blackbeard",   "Attacker",     "Support",                          2, 1,   1,                  "Navy SEAL",                "Redhammer",       	1.80,	84,	    32,	    "USA"]    
export const Capitao = [        "Capitao",  	"Attacker",     "Front-Line, Map-Control",          3, 2,   1,                  "BOPE",                     "Viperstrike",     	1.83,	86,	    49,	    "Brazil"]    
export const Hibana = [         "Hibana",   	"Attacker",     "Breacher, Front-Line",             3, 1,   1,                  "SAT",                      "Viperstrike",     	1.73,	57,	    34,	    "Japan"]
export const Jackal = [         "Jackal",   	"Attacker",     "Intel, Map-Control",               2, 3,   2,                  "GEO",                      "Viperstrike",     	1.90,	78,	    49,	    "Spain"]
export const Ying = [           "Ying",     	"Attacker",     "Front-Line, Map-Control",          2, 2,   2,                  "SDU",                      "Wolfguard",       	1.60,	52,	    33,	    "Hong Kong"]
export const Zofia = [          "Zofia",    	"Attacker",     "Breacher, Anti-Gadget",            1, 1,   2,                  "GROM",                     "Ghosteyes",       	1.79,	72,	    36,	    "Poland"]
export const Dokkaebi = [       "Dokkaebi",     "Attacker",     "Intel, Map-Control",               3, 2,   2,                  "707th SMB",                "Viperstrike",     	1.69,	62,	    29,	    "South Korea"]    
export const Lion = [           "Lion",     	"Attacker",     "Intel, Map-Control",               2, 1,   3,                  "CBRN Threat Unit",         "Wolfguard",       	1.85,	87,	    31,	    "France"]
export const Finka = [          "Finka",    	"Attacker",     "Support, Front-Line",              2, 1,   3,                  "CBRN Threat Unit",         "Nighthaven",      	1.71,	68,	    27,	    "Belarus"]
export const Maverick = [       "Maverick", 	"Attacker",     "Breacher, Front-Line",             3, 2,   3,                  "GSUTR",                    "Ghosteyes",       	1.80,	82,	    36,	    "USA"]    
export const Nomad = [          "Nomad",    	"Attacker",     "Front-Line, Map-Control",          2, 3,   3,                  "GIGR",                     "Wolfguard",       	1.71,	63,	    39,	    "Morocco"]
export const Gridlock = [       "Gridlock", 	"Attacker",     "Support, Map-Control",             1, 1,   4,                  "SASR",                     "Redhammer",       	1.77,	102,    36,	    "Australia"]    
export const Amaru = [          "Amaru",    	"Attacker",     "Front-Line, Map-Control",          2, 2,   4,                  "APCA",                     "Redhammer",       	1.89,	84,	    48,	    "Peru"]
export const Kali = [           "Kali",     	"Attacker",     "Anti-Gadget, Support",             2, 2,   4,                  "Nighthaven",               "Nighthaven",      	1.70,	67,	    34,	    "India"]
export const Iana = [           "Iana",     	"Attacker",     "Intel, Front-Line",                2, 1,   5,                  "REU",                      "Ghosteyes",       	1.57,	56,	    35,	    "Netherlands"]
export const Ace = [            "Ace",          "Attacker",     "Breacher, Anti-Gadget",            2, 1,   5,                  "Nighthaven",               "Nighthaven",       1.87,   75,     33,     "Norway"]
export const Zero = [           "Zero",     	"Attacker",     "Intel, Anti-Gadget",               3, 1,   5,                  "ROS",                      "Ghosteyes",       	1.78,	77,	    63,	    "USA"]
export const Flores = [         "Flores",   	"Attacker",     "Intel, Anti-Gadget",               2, 2,   6,                  "Unaffiliated",             "Ghosteyes",       	1.81,	72,	    38,	    "Argentina"]
export const Osa = [            "Osa",      	"Attacker",     "Intel, Support",                   1, 2,   6,                  "Nighthaven",               "Nighthaven",      	1.80,	71,	    27,	    "Croatia"]
export const Sens = [           "Sens",     	"Attacker",     "Support, Map-Control",             3, 2,   7,                  "SFG",                      "Wolfguard",       	1.78,	73,	    30,	    "Belgium"]
export const Grim = [           "Grim",     	"Attacker",     "Front-Line, Map-Control",          3, 1,   7,                  "Nighthaven",               "Nighthaven",      	1.79,	89,	    39,	    "Singapore"]
export const Brava = [          "Brava",    	"Attacker",     "Intel, Anti-Gadget",               3, 3,   8,                  "COT",                      "Viperstrike",     	1.70,	71,	    40,	    "Brazil"]
export const Ram = [            "Ram",      	"Attacker",     "Breacher",                         1, 2,   8,                  "35th Commando Battalion",  "Redhammer",       	1.78,	68,	    37,	    "South Korea"]

export const Smoke = [          "Smoke",    	"Defender",     "Trapper, Anti-Entry",              2, 2,   0,                  "SAS",                      "Nighthaven",      	1.73,	70,	    36,	    "England"]
export const Mute = [           "Mute",     	"Defender",     "Anti-Gadget, Crowd-Control",       1, 1,   0,                  "SAS",                      "Viperstrike",     	1.85,	80,	    25,	    "England"]
export const Castle = [         "Castle",   	"Defender",     "Support, Anti-Entry",              2, 2,   0,                  "FBI SWAT",                 "Wolfguard",       	1.85,	86,	    36,	    "USA"]
export const Pulse = [          "Pulse",    	"Defender",     "Intel, Support",                   3, 3,   0,                  "FBI SWAT",                 "Nighthaven",      	1.88,	85,	    32,	    "USA"]
export const Doc = [            "Doc",      	"Defender",     "Support",                          1, 1,   0,                  "GIGN",                     "Wolfguard",       	1.77,	74,	    39,	    "France"]
export const Rook = [           "Rook",     	"Defender",     "Support",                          1, 1,   0,                  "GIGN",                     "Viperstrike",     	1.75,	72,	    27,	    "France"]
export const Kapkan = [         "Kapkan",   	"Defender",     "Trapper, Anti-Entry",              2, 1,   0,                  "Spetsnaz",                 "Redhammer",       	1.80,	80,	    38,	    "Russia"]
export const Tachanka = [       "Tachanka", 	"Defender",     "Anti-Entry, Crowd-Control",        1, 1,   0,                  "Spetsnaz",                 "Redhammer",       	1.83,	86,	    48,	    "Russia"]    
export const Jager = [          "Jager",    	"Defender",     "Anti-Gadget, Support",             2, 2,   0,                  "GSG 9",                    "Viperstrike",     	1.80,	64,	    39,	    "Germany"]
export const Bandit = [         "Bandit",   	"Defender",     "Anti-Gadget, Anti-Entry",          3, 1,   0,                  "GSG 9",                    "Wolfguard",       	1.80,	68,	    42,	    "Germany"]
export const Frost = [          "Frost",    	"Defender",     "Trapper, Anti-Entry",              2, 1,   1,                  "JTF2",                     "Wolfguard",       	1.72,	63,	    32,	    "Canada"]
export const Valkyrie = [       "Valkyrie", 	"Defender",     "Intel, Support",                   2, 2,   1,                  "Navy SEAL",                "Ghosteyes",       	1.70,	61,	    31,	    "USA"]    
export const Caveira = [        "Caveira",  	"Defender",     "Intel, Crowd-Control",             3, 3,   1,                  "BOPE",                     "Ghosteyes",       	1.77,	72,	    27,	    "Brazil"]    
export const Echo = [           "Echo",     	"Defender",     "Intel, Crowd-Control",             2, 3,   1,                  "SAT",                      "Viperstrike",     	1.80,	72,	    36,	    "Japan"]
export const Mira = [           "Mira",     	"Defender",     "Intel, Support",                   1, 3,   2,                  "GEO",                      "Viperstrike",     	1.65,	60,	    39,	    "Spain"]
export const Lesion = [         "Lesion",   	"Defender",     "Trapper, Anti-Entry",              2, 1,   2,                  "SDU",                      "Ghosteyes",        1.74,	82,	    44,	    "Hong Kong"]
export const Ela = [            "Ela",      	"Defender",     "Trapper, Crowd-Control",           2, 1,   2,                  "GROM",                     "Nighthaven",      	1.73,	68,	    31,	    "Poland"]
export const Vigil = [          "Vigil",    	"Defender",     "Anti-Gadget, Crowd-Control",       3, 3,   2,                  "707th SMB",                "Ghosteyes",       	1.73,	73,	    34,	    "NULL"]
export const Maestro = [        "Maestro",  	"Defender",     "Intel, Anti-Gadget",               1, 2,   3,                  "GIS",                      "Viperstrike",     	1.85,	87,	    45,	    "Italy"]    
export const Alibi = [          "Alibi",        "Defender",     "Trapper, Intel",                   3, 3,   3,                  "GIS",                      "Viperstrike",      1.71,   63,     37,     "Libya"]
export const Clash = [          "Clash",    	"Defender",     "Intel, Crowd-Control",             1, 3,   3,                  "GSUTR",                    "Wolfguard",       	1.79,	73,	    35,	    "England"]
export const Kaid = [           "Kaid",     	"Defender",     "Anti-Gadget, Anti-Entry",          1, 2,   3,                  "GIGR",                     "Redhammer",       	1.95,	98,	    58,	    "Morocco"]
export const Mozzie = [         "Mozzie",   	"Defender",     "Intel, Anti-Gadget",               2, 2,   4,                  "SASR",                     "Ghosteyes",       	1.62,	57,	    35,	    "Australia"]
export const Warden = [         "Warden",   	"Defender",     "Intel, Anti-Gadget",               1, 2,   4,                  "Secret Service",           "Ghosteyes",       	1.83,	80,	    48,	    "USA"]
export const Goyo = [           "Goyo",     	"Defender",     "Trapper, Anti-Entry",              2, 2,   4,                  "Fuerzas Especiales",       "Redhammer",       	1.71,	83,	    31,	    "Mexico"]
export const Wamai = [          "Wamai",    	"Defender",     "Trapper, Anti-Gadget",             2, 2,   4,                  "Nighthaven",               "Nighthaven",      	1.87,	83,	    28,	    "Kenya"]
export const Oryx = [           "Oryx",     	"Defender",     "Support",                          2, 2,   5,                  "Unaffiliated",             "Redhammer",       	1.95,	130,    45,	    "Jordan"]
export const Melusi = [         "Melusi",   	"Defender",     "Intel, Crowd-Control",             1, 1,   5,                  "Inkaba Task Force",        "Wolfguard",       	1.72,	68,	    32,	    "South Africa"]
export const Aruni = [          "Aruni",    	"Defender",     "Anti-Gadget, Anti-Entry",          1, 2,   5,                  "Nighthaven",               "Nighthaven",      	1.60,	58,	    42,	    "Thailand"]
export const Thunderbird = [    "Thunderbird",  "Defender",     "Support",                          2, 1,   6,                  "tar-NET Aviation",         "Wolfguard",       	1.72,	70,	    36,	    "Cananda"]        
export const Thorn = [          "Thorn",    	"Defender",     "Trapper, Anti-Entry",              2, 1,   6,                  "Emergency Response Unit",  "Redhammer",       	1.88,	78,	    28,	    "Ireland"]
export const Azami = [          "Azami",    	"Defender",     "Support, Anti-Entry",              2, 3,   7,                  "Unaffiliated",             "Viperstrike",     	1.64,	56,	    28,	    "Japan"]
export const Solis = [          "Solis",    	"Defender",     "Intel, Support",                   2, 3,   7,                  "AFEAU",                    "Ghosteyes",       	1.66,	65,	    37,	    "Colombia"]
export const Fenrir = [         "Fenrir",   	"Defender",     "Trapper",                          2, 3,   8,                  "Unaffiliated",             "Redhammer",       	1.76,	74,	    34,	    "Sweden"]

export const Nokk = [           "Nokk",     	"Attacker",     "Front-Line, Map-Control",          2, 3,   4,                  "Jarger Corps",             "Ghosteyes",       	"REDACTED",	"REDACTED",	"REDACTED",	"REDACTED"]
export const OperatorInfo = [Ace,Alibi,Amaru,Aruni,Ash,Azami,Bandit,Blackbeard,Blitz,Brava,Buck,Capitao,Castle,Caveira,
                            Clash,Doc,Dokkaebi,Echo,Ela,Fenrir,Finka,Flores,Frost,Fuze,Glaz,Goyo,Gridlock,
                            Grim,Hibana,Iana,Iq,Jackal,Jager,Kaid,Kali,Kapkan,Lesion,Lion,Maestro,Maverick,Melusi,
                            Mira,Montagne,Mozzie,Mute,Nokk,Nomad,Oryx,Osa,Pulse,Ram,Rook,Sens,Sledge,Smoke,Solis,
                            Tachanka,Thatcher,Thermite,Thorn,Thunderbird,Twitch,Valkyrie,Vigil,Wamai,Warden,Ying,Zero,Zofia]